# Exception

try:
    a = int(input('Enter user value : '))
    print(10/a)
    print('Micky'+a) 
except Exception as e:
    print('Exception  : ',e) 


print()
print('Rest of the code...')



